### ISSUE TITLE
Support typescript ??

### ISSUE THREAD

**Issue by wzalazar** [emilbayes/secure-password#12]
> Could not find a declaration file for module 'secure-password'. 
>   Try `npm install @types/secure-password` if it exists or add a new declaration (.d.ts) file containing `declare module 'secure-password';`

**Comment by emilbayes** [comment]
maybe someone else would be willing to contribute this? I don't know typescript and don't use it, so I'm afraid that it would simply bitrot over time (not that I plan any major changes)
