### ISSUE TITLE
Would recommend updating ReadMe/docs to be more specific on how the algorithm is chosen.

### ISSUE THREAD

**Issue by cakoose** [emilbayes/secure-password#27]
Hi!  The docs currently say that Argon2id is used, which roughly correct.  But more precisely, it uses libsodium's current default password hashing algorithm, which may change in the future, but will always be backwards compatible.

I realize not everybody needs that level of precision, but because NPM has a lot of low-quality packages, I usually dig in a little when it's something important like crypto.  My rough thought process:
1. I need a library to do Argon2id.  I found secure-password.
2. Looks like it uses libsodium -- this is good because I know libsodium is optimized native code, which is very important for password hashing to make sure we're not giving the attacker an unnecessary CPU advantage.  I avoided the NPM package that used the Argon2id reference implementation because I assumed (perhaps incorrectly) that the reference implementation might not be optimized as well as libsodium.
3. Looks like it uses `sodium.crypto_pwhash` and not `sodium.crypto_pwhash_argon2id`.  What if libsodium changes their default in the future?  For example, will the `crypto_pwhash_PASSWD_MIN` constants change and cause incompatibilities in the future?
4. I then read the libsodium docs which say that the `crypto_pwhash` will remain backwards compatible ([link](https://libsodium.gitbook.io/doc/password_hashing)):

> Sodium's high-level `crypto_pwhash_*` API currently leverages the Argon2id function on all platforms. This can change at any point in time, but it is guaranteed that a given version of libsodium can verify all hashes produced by all previous versions, from any platform. Applications don't have to worry about backward compatibility.

I think something like this at the top of the ReadMe and NPM docs would have saved me some effort:

> Uses [sodium-native](https://www.npmjs.com/package/sodium-native) package to call [libsodium](https://github.com/jedisct1/libsodium)'s optimized `crypto_pwhash` API, which currently defaults **[Argon2id](https://en.wikipedia.org/wiki/Argon2)**.  libsodium promises the `crypto_pwhash` API will remain backwards compatible, even if they change the default algorithm (search for "previous versions" or "backwards compatibility" in the [libsodium pwhash docs](https://libsodium.gitbook.io/doc/password_hashing)).

**Comment by emilbayes** [comment]
To answer:
3. If the default algorithm changes, this module will get a semver major bump. However the "string" that comes out of that function, has all hashing parameters baked in, including the hashing algorithm :)
4. Yes, the backwards compatibilities lies in the parameters baked into the "hash" (which actually an ascii string of all parameters)

**Comment by cakoose** [comment]
Oh, that's good to know.

Please consider adding that to the ReadMe, so that people don't have to dig into the code to learn this.  For example, a very simple change might be to extend the first bullet point from:

> - State of the art password hashing algorithm (Argon2id)

to:

> - State of the art password hashing algorithm (Argon2id via [libsodium](https://www.npmjs.com/package/libsodium))
