### ISSUE TITLE
Node 4 support?

### ISSUE THREAD

**Issue by YerkoPalma** [emilbayes/secure-password#4]
Hi :wave:,
I'm using `secure-password` with node 7 and works great. I've defined some tests that are all passing locally, but are failling in travis for node 4. Is this module not supporting node 4 or am I doing something wrong? Here is the travis log: https://travis-ci.org/YerkoPalma/auth-example/builds/248086860

Seems like some assertion is throwing, but just for node 4.
Thanks :)

**Comment by emilbayes** [comment]
I'll try to figure out what went wrong when I'm back from holidays. The only dependency this module wraps has support all the way back to 0.10. I'm back next Monday :)

**Comment by emilbayes** [comment]
I'm the meantime try and print out the hash from both your signup and signin routes. The hash buffers are ascii printable :)

**Comment by YerkoPalma** [comment]
I guess you are asking me to print `hash.toString('ascii')`. In that case, I printed in the signin view and signup view the hash and this is what I get:

```bash
$ node -v
v7.7.4
$ npm start

> auth-example@1.0.0 start /home/ubuntu/workspace/auth-example
> node index.js

server running on 0.0.0.0:8080
signup $argon2i$v=19$m=32768,t=4,p=1$5kC2W4EY8Pb+ryBdNhCnNA$IUs6RlGjnfPoL8jsyxS/PR1Nh4+TDYfR5ftIwsG4Ldc
signin $argon2i$v=19$m=32768,t=4,p=1$5kC2W4EY8Pb+ryBdNhCnNA$IUs6RlGjnfPoL8jsyxS/PR1Nh4+TDYfR5ftIwsG4Ldc
^C
```

```bash
$ node -v
v4.4.5
$ npm start

> auth-example@1.0.0 start /home/ubuntu/workspace/auth-example
> node index.js

{"pid":4035,"hostname":"yerkopalma-playground-3665860","name":"merry","level":60,"time":1498764846823,"msg":"this is not a typed array.","type":"Error","stack":"TypeError: this is not a typed array.\n    at Function.from (native)\n    at html (/home/ubuntu/workspace/auth-example/node_modules/bankai/index.js:58:19)\n    at EventEmitter.Bankai (/home/ubuntu/workspace/auth-example/node_modules/bankai/index.js:48:16)\n    at Bankai (/home/ubuntu/workspace/auth-example/node_modules/bankai/index.js:27:41)\n    at Object.<anonymous> (/home/ubuntu/workspace/auth-example/index.js:6:14)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Function.Module.runMain (module.js:441:10)","v":1}
TypeError: this is not a typed array.
    at Function.from (native)
    at html (/home/ubuntu/workspace/auth-example/node_modules/bankai/index.js:58:19)
    at EventEmitter.Bankai (/home/ubuntu/workspace/auth-example/node_modules/bankai/index.js:48:16)
    at Bankai (/home/ubuntu/workspace/auth-example/node_modules/bankai/index.js:27:41)
    at Object.<anonymous> (/home/ubuntu/workspace/auth-example/index.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

So, that node version throws a different error, related to the `Buffer.from()` method, I guess that that's because of the last `Buffer new` deprecation not being backported (I'm just guessing). So I've tried with the exact node version used in travis (4.8.3), and got this:

```bash
$ npm start

> auth-example@1.0.0 start /home/ubuntu/workspace/auth-example
> node index.js

server running on 0.0.0.0:8080
signup $argon2i$v=19$m=32768,t=4,p=1$RZGSpkgTKI5n6ua9NBR84g$t1lIiIK0XbPlr/T7OnDilgd6Op2Wi5Q1s5JYZ4+3RCk
signin $argon2i$v=19$m=32768,t=4,p=1$RZGSpkgTKI5n6ua9NBR84g$t1lIiIK0XbPlr/T7OnDilgd6Op2Wi5Q1s5JYZ4+3RCk
{"pid":4604,"hostname":"yerkopalma-playground-3665860","name":"merry","level":60,"time":1498765274226,"msg":"Hash is missing type","type":"Error","stack":"AssertionError: Hash is missing type\n    at decodeArgon2iStr (/home/ubuntu/workspace/auth-example/node_modules/secure-password/index.js:125:3)\n    at SecurePassword.<anonymous> (/home/ubuntu/workspace/auth-example/node_modules/secure-password/index.js:103:22)","name":"AssertionError","actual":false,"expected":true,"operator":"==","message":"Hash is missing type","generatedMessage":false,"v":1}
AssertionError: Hash is missing type
    at decodeArgon2iStr (/home/ubuntu/workspace/auth-example/node_modules/secure-password/index.js:125:3)
    at SecurePassword.<anonymous> (/home/ubuntu/workspace/auth-example/node_modules/secure-password/index.js:103:22)
```

As you can see the ascii representations of the hash are the same, but for some reason the assertion is throwing. I suspect that is related to the Buffer module and not directly with this module or `sodium-native` but I'm not sure why or how to avoid this. Should I use `Buffer new` for older node versions? or just drop support for those versions? Or are there any other better way/lib to generate a buffer from a string in older node versions?

Anyway, enjoy your holidays, I'll wait until monday
Thanks :)

**Comment by emilbayes** [comment]
So I didn't realise the `buf.compare(other, offset, end)` with the two last arguments was a new feature. I have back-ported the code so it [now works on `node@4`](https://travis-ci.org/emilbayes/secure-password/builds/249814796). Enjoy!

**Comment by YerkoPalma** [comment]
Awesome, will update now. Thanks.
