### ISSUE TITLE
Sodium variable are undefined for the javascript version

### ISSUE THREAD

**Issue by timmak** [emilbayes/secure-password#9]
`Error: opts.memlimit must be at least MEMLIMIT_MIN (undefined)`

Seems the js version of sodium does not include the variables. Also `sodium.crypto_pwhash_str_async` seems to be missing in the js version

**Comment by emilbayes** [comment]
Hi @timmak,

Argon2i is not part of `sodium-javascript` which is the browser version of `sodium-native`. I don't know if we will implement it as will take considerable time to do so and test thoroughly, so I should probably change the dependency from `sodium-universal` to `sodium-native`. What's your usecase?

**Comment by timmak** [comment]
Completely understand, was trying to use it with [https://github.com/zeit/pkg]() which was resolving to the javascript one. Still trying to get it to work with the `sodium-native` but this is different issue to the one above.

**Comment by emilbayes** [comment]
You can find me on IRC in #choo and #stackvm if you need help :)

**Comment by emilbayes** [comment]
Please reopen if you have more to share about using `secure-password` with `pkg`
